runtime: python312

handlers:
  - url: /style.css
    static_files: style.css
    upload: style.css

  - url: /script.js
    static_files: script.js
    upload: script.js

  - url: /.*
    static_files: index.html
    upload: index.html
