# API Testing
GET http://localhost:8080/ HTTP/1.1

###
# GET : All Notes
GET http://localhost:8080/api/v1/notes HTTP/1.1
Content-Type: application/json

###
# GET : Note by ID
GET http://localhost:8080/api/v1/notes/1 HTTP/1.1
Content-Type: application/json

###
# POST : Create Note
POST http://localhost:8080/api/v1/notes HTTP/1.1
Content-Type: application/json

{
  "judul": "Tes Api",
  "isi": "Tes Api Notes App"
}

###
# PUT : Update Note
PUT http://localhost:8080/api/v1/notes/1 HTTP/1.1
Content-Type: application/json

{
    "judul": "Tes Api (Update)",
  "isi": "Tes Api Notes App (Update)"
}

###
# DELETE : Delete Note
DELETE http://localhost:8080/api/v1/notes/1 HTTP/1.1
Content-Type: application/json
